### PR TITLE
uname for password resets

### PR DESCRIPTION
**Pull request by cubap**
This should manage the password issue, and names things more clearly, but doesn't rewrite the whole UX.

### CODE REVIEW

**Comment by cubap** [comment]
fixes #155

**Comment by cubap** [comment]
fixes #148

**Comment by thehabes** [comment]
Merged into PR #149 for testing.  Closing this PR.

**Comment by thehabes** [comment]
Tested and functional.  Now closing it without merging, we will merge these in through #149

**Pull request closed without merging**
