### PR TITLE
header/footer templates

### PR DESCRIPTION
**Pull request by cubap**
This works locally for me. You want to give it a look? I'll update the links and such in the actual templates separately from getting them onto the page.

### CODE REVIEW

**Comment by cubap** [comment]
closes #59

**Comment by cubap** [comment]
Make sure to omit on transcription interfaces.
Move tpen.js import to the end.

**Comment by cubap** [comment]
move to newberry.js

**Comment by cubap** [comment]
@thehabes You can take a shot at this one now, if you like. I'll move to the other repo to change the content.

**Review by thehabes — APPROVED** [review]
That did it!

**Pull request merged**
