### PR TITLE
Connect essays

### PR DESCRIPTION
**Pull request by cubap**
A sample essay and transcription are in place for each of the MSs provided as demo. (314 and 003 in Italian)

Direct links for what you should be seeing:

- transcription of St. Jerome https://centerfordigitalhumanities.github.io/Newberry-Italian-paleography/transcriptions/003
- essay of St. Jerome https://centerfordigitalhumanities.github.io/Newberry-Italian-paleography/essay/003
- transcription of Art of Cooking https://centerfordigitalhumanities.github.io/Newberry-Italian-paleography/transcriptions/314
- essay of Art of Cooking https://centerfordigitalhumanities.github.io/Newberry-Italian-paleography/essay/314

### CODE REVIEW

**Comment by cubap** [comment]
I know this doesn't look like much, but it is all set up in the other repos to find things right where you expect them and will "just work" for all the other MSS we add.

**Comment by cubap** [comment]
possible fix: canvas IDs are like FP_001_001 and IP_001_001 which would solve my issue local to this, but doesn't leave it simple for you to find out where to go on the home page.

**Comment by thehabes** [comment]
Yeah yeah I see what you did there.  Looks good, though we will definitely need to test against it and make sure we do all the naming convention stuff right.

**Review by thehabes — APPROVED** [review]
This is a general naming convention thing we will have to make sure we respect in script and db data as we move forward.  Looks good for now.

**Pull request merged**
